package main

/* This file is automatically generated */
//######################################//

const (
	CliValuePort         = "port"
	CliValueBaudConnect  = "baudConnect"
	CliValueBaudTransfer = "baudTransfer"

	CliValueConnTimeout = "connTimeout"
	CliValueConnRetries = "connRetries"

	CliValueFlashCompress = "flashCompress"
	CliValueFlashOffset   = "flashOffset"
	CliValueFlashSize     = "flashSize"
	CliValueFlashFile     = "flashFile"
	CliValueFlashName     = "flashName"
)

const (
	CliValueTextPort         = "Device name or path"
	CliValueTextBaudConnect  = "Serial signalling rate during connect phase"
	CliValueTextBaudTransfer = "Serial signalling rate during data transfer"

	CliValueTextConnTimeout = "Timeout to wait for chip response upon connecting"
	CliValueTextConnRetries = "How often to retry connecting"

	CliValueTextFlashCompress = "Use compression for transfer"
	CliValueTextFlashOffset   = "The point where we start"
	CliValueTextFlashSize     = "How many bytes do we capture?"
	CliValueTextFlashFile     = "File path"
	CliValueTextFlashName     = "Partition name"
)
