package main

import "flag"

/* This file is automatically generated */
//######################################//

const (
	CliTrigShowAHelpPage                   = "help"
	CliTrigShowApplicationBuildInformation = "version"

	CliTrigOutputResponsesInJson             = "json"
	CliTrigDisplayAnswersWithoutColorization = "noColor"

	CliTrigGetAListOfAvailableCOMDevices   = "list"
	CliTrigShowESPInformation              = "info"
	CliTrigReadingFirmwareFromESPToFile    = "flashRead"
	CliTrigRecordingFirmwareFromAFileInESP = "flashWrite"
)

const (
	CliTrigTextShowAHelpPage                   = "Show a help page"
	CliTrigTextShowApplicationBuildInformation = "Show application build information"

	CliTrigTextOutputResponsesInJson             = "Output responses in json"
	CliTrigTextDisplayAnswersWithoutColorization = "Display answers without colorization"

	CliTrigTextGetAListOfAvailableCOMDevices   = "Get a list of available COM devices"
	CliTrigTextShowESPInformation              = "Show ESP information"
	CliTrigTextReadingFirmwareFromESPToFile    = "Reading firmware from ESP to file"
	CliTrigTextRecordingFirmwareFromAFileInESP = "Recording firmware from a file in ESP"
)

type CliTrigTypeObj struct {
	Help    *bool
	Version *bool

	Json    *bool
	NoColor *bool

	List       *bool
	Info       *bool
	FlashRead  *bool
	FlashWrite *bool
}

var CliTrigType = CliTrigTypeObj{
	Help:       flag.Bool(CliTrigShowAHelpPage, false, CliTrigTextShowAHelpPage),
	Version:    flag.Bool(CliTrigShowApplicationBuildInformation, false, CliTrigTextShowApplicationBuildInformation),
	Json:       flag.Bool(CliTrigOutputResponsesInJson, false, CliTrigTextOutputResponsesInJson),
	NoColor:    flag.Bool(CliTrigDisplayAnswersWithoutColorization, false, CliTrigTextDisplayAnswersWithoutColorization),
	List:       flag.Bool(CliTrigGetAListOfAvailableCOMDevices, false, CliTrigTextGetAListOfAvailableCOMDevices),
	Info:       flag.Bool(CliTrigShowESPInformation, false, CliTrigTextShowESPInformation),
	FlashRead:  flag.Bool(CliTrigReadingFirmwareFromESPToFile, false, CliTrigTextReadingFirmwareFromESPToFile),
	FlashWrite: flag.Bool(CliTrigRecordingFirmwareFromAFileInESP, false, CliTrigTextRecordingFirmwareFromAFileInESP),
}
