package code

/* This file is automatically generated */

type DirectionType byte

const (
	DirectionRequest  DirectionType = 0 //0x00
	DirectionResponse DirectionType = 1 //0x01
)

const (
	DirectionTextRequest  = "Request"
	DirectionTextResponse = "Response"
)

var DirectionMap = map[DirectionType]string{
	DirectionRequest:  DirectionTextRequest,
	DirectionResponse: DirectionTextResponse,
}

func (obj DirectionType) String() string {
	val, ok := DirectionMap[obj]
	if ok {
		return val
	}
	return "Unknown DirectionType"
}
