package code

/* This file is automatically generated */

type EspType byte

const (
	EspESP32D0WDQ6 EspType = 0 //0x00
	EspESP32D0WDQ5 EspType = 1 //0x01
	EspESP32D2WDQ5 EspType = 2 //0x02
	EspESP32PICOD4 EspType = 5 //0x05
)

const (
	EspTextESP32D0WDQ6 = "ESP32 D0-WD Q6"
	EspTextESP32D0WDQ5 = "ESP32 D0-WD Q5"
	EspTextESP32D2WDQ5 = "ESP32 D2-WD Q5"
	EspTextESP32PICOD4 = "ESP32 PICO D4"
)

var EspMap = map[EspType]string{
	EspESP32D0WDQ6: EspTextESP32D0WDQ6,
	EspESP32D0WDQ5: EspTextESP32D0WDQ5,
	EspESP32D2WDQ5: EspTextESP32D2WDQ5,
	EspESP32PICOD4: EspTextESP32PICOD4,
}

func (obj EspType) String() string {
	val, ok := EspMap[obj]
	if ok {
		return val
	}
	return "Unknown EspType"
}
