package code

/* This file is automatically generated */
//######################################//

type FeatureType byte

const (
	FeatureWiFi      FeatureType = 1
	FeatureBluetooth FeatureType = 2

	FeatureSingleCore FeatureType = 31
	FeatureDualCore   FeatureType = 32

	Feature80MHz  FeatureType = 51
	Feature160MHz FeatureType = 52
	Feature240MHz FeatureType = 53
	Feature320MHz FeatureType = 54

	FeatureEmbeddedFlash         FeatureType = 101
	FeatureVRefCalibration       FeatureType = 102
	FeatureBLK3PartiallyReserved FeatureType = 103

	FeatureCodingSchemeNone    FeatureType = 151
	FeatureCodingScheme34      FeatureType = 152
	FeatureCodingSchemeRepeat  FeatureType = 153
	FeatureCodingSchemeInvalid FeatureType = 154
)

const (
	FeatureTextWiFi      = "WiFi"
	FeatureTextBluetooth = "Bluetooth"

	FeatureTextSingleCore = "Single Core"
	FeatureTextDualCore   = "Dual Core"

	FeatureText80MHz  = "80MHz"
	FeatureText160MHz = "160MHz"
	FeatureText240MHz = "240MHz"
	FeatureText320MHz = "320MHz"

	FeatureTextEmbeddedFlash         = "Embedded Flash"
	FeatureTextVRefCalibration       = "VRef calibration"
	FeatureTextBLK3PartiallyReserved = "BLK3 partially reserved"

	FeatureTextCodingSchemeNone    = "Coding Scheme None"
	FeatureTextCodingScheme34      = "Coding Scheme 3/4"
	FeatureTextCodingSchemeRepeat  = "Coding Scheme Repeat"
	FeatureTextCodingSchemeInvalid = "Coding Scheme Invalid"
)

var FeatureMap = map[FeatureType]string{
	FeatureWiFi:                  FeatureTextWiFi,
	FeatureBluetooth:             FeatureTextBluetooth,
	FeatureSingleCore:            FeatureTextSingleCore,
	FeatureDualCore:              FeatureTextDualCore,
	Feature80MHz:                 FeatureText80MHz,
	Feature160MHz:                FeatureText160MHz,
	Feature240MHz:                FeatureText240MHz,
	Feature320MHz:                FeatureText320MHz,
	FeatureEmbeddedFlash:         FeatureTextEmbeddedFlash,
	FeatureVRefCalibration:       FeatureTextVRefCalibration,
	FeatureBLK3PartiallyReserved: FeatureTextBLK3PartiallyReserved,
	FeatureCodingSchemeNone:      FeatureTextCodingSchemeNone,
	FeatureCodingScheme34:        FeatureTextCodingScheme34,
	FeatureCodingSchemeRepeat:    FeatureTextCodingSchemeRepeat,
	FeatureCodingSchemeInvalid:   FeatureTextCodingSchemeInvalid,
}

func (obj FeatureType) String() string {
	val, ok := FeatureMap[obj]
	if ok {
		return val
	}
	return "Unknown FeatureType"
}
