package code

/* This file is automatically generated */
//######################################//

type FeatureType byte

const (
	FeatureWiFi      FeatureType = 1
	FeatureBluetooth FeatureType = 2

	FeatureSingleCore FeatureType = 31
	FeatureDualCore   FeatureType = 32

	FeatureClock80MHz  FeatureType = 51
	FeatureClock160MHz FeatureType = 52
	FeatureClock240MHz FeatureType = 53
	FeatureClock320MHz FeatureType = 54

	FeatureEmbeddedFlash         FeatureType = 101
	FeatureVRefCalibration       FeatureType = 102
	FeatureBLK3PartiallyReserved FeatureType = 103

	FeatureCodingSchemeNone    FeatureType = 151
	FeatureCodingScheme34      FeatureType = 152
	FeatureCodingSchemeRepeat  FeatureType = 153
	FeatureCodingSchemeInvalid FeatureType = 154
)

const (
	FeatureTextWiFi      = "WiFi"
	FeatureTextBluetooth = "Bluetooth"

	FeatureTextSingleCore = "Single Core"
	FeatureTextDualCore   = "Dual Core"

	FeatureTextClock80MHz  = "Clock 80MHz"
	FeatureTextClock160MHz = "Clock 160MHz"
	FeatureTextClock240MHz = "Clock 240MHz"
	FeatureTextClock320MHz = "Clock 320MHz"

	FeatureTextEmbeddedFlash         = "Embedded Flash"
	FeatureTextVRefCalibration       = "VRef calibration"
	FeatureTextBLK3PartiallyReserved = "BLK3 partially reserved"

	FeatureTextCodingSchemeNone    = "Coding Scheme None"
	FeatureTextCodingScheme34      = "Coding Scheme 3/4"
	FeatureTextCodingSchemeRepeat  = "Coding Scheme Repeat"
	FeatureTextCodingSchemeInvalid = "Coding Scheme Invalid"
)

var FeatureMap = map[FeatureType]string{
	FeatureWiFi:                  FeatureTextWiFi,
	FeatureBluetooth:             FeatureTextBluetooth,
	FeatureSingleCore:            FeatureTextSingleCore,
	FeatureDualCore:              FeatureTextDualCore,
	FeatureClock80MHz:            FeatureTextClock80MHz,
	FeatureClock160MHz:           FeatureTextClock160MHz,
	FeatureClock240MHz:           FeatureTextClock240MHz,
	FeatureClock320MHz:           FeatureTextClock320MHz,
	FeatureEmbeddedFlash:         FeatureTextEmbeddedFlash,
	FeatureVRefCalibration:       FeatureTextVRefCalibration,
	FeatureBLK3PartiallyReserved: FeatureTextBLK3PartiallyReserved,
	FeatureCodingSchemeNone:      FeatureTextCodingSchemeNone,
	FeatureCodingScheme34:        FeatureTextCodingScheme34,
	FeatureCodingSchemeRepeat:    FeatureTextCodingSchemeRepeat,
	FeatureCodingSchemeInvalid:   FeatureTextCodingSchemeInvalid,
}

func (obj FeatureType) String() string {
	val, ok := FeatureMap[obj]
	if ok {
		return val
	}
	return "Unknown FeatureType"
}
