package code

/* This file is automatically generated */

type StateType byte

const (
	StateWaitingHeader  StateType = 0 //0x00
	StateReadingContent StateType = 1 //0x01
	StateInEscape       StateType = 2 //0x02
)

const (
	StateTextWaitingHeader  = "Waiting Header"
	StateTextReadingContent = "Reading Content"
	StateTextInEscape       = "In Escape"
)

var StateMap = map[StateType]string{
	StateWaitingHeader:  StateTextWaitingHeader,
	StateReadingContent: StateTextReadingContent,
	StateInEscape:       StateTextInEscape,
}

func (obj StateType) String() string {
	val, ok := StateMap[obj]
	if ok {
		return val
	}
	return "Unknown StateType"
}
