package core

/* This file is automatically generated */
//######################################//

var ESP32C2ROM = ModulStruct{
	Name: "ESP32-C2",

	Sys: ModulSystemStruct{
		UF2:         730387100,
		Chip:        12,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{1867591791, 2084675695},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"DROM":            {1006632960, 1010827264},
		"BYTE_ACCESSIBLE": {1070104576, 1070596096},
		"DRAM":            {1070202880, 1070465024},
		"DROM_MASK":       {1072693248, 1073020928},
		"IROM_MASK":       {1073741824, 1074331648},
		"IRAM":            {1077395456, 1077673984},
		"IROM":            {1107296256, 1111490560},
	},
}
