package core

/* This file is automatically generated */
//######################################//

var ESP32H2ROM = ModulStruct{
	Name: "ESP32-H2",

	Sys: ModulSystemStruct{
		UF2:         858203894,
		Chip:        16,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{3619110528},
	Memory:     map[string]ModulMapStruct{},
}
