package core

/* This file is automatically generated */
//######################################//

var ESP32S2ROM = ModulStruct{
	Name: "ESP32-S2",

	Sys: ModulSystemStruct{
		UF2:         3218951918,
		Chip:        2,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{1990},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"DROM":            {1056964608, 1073217536},
		"EXTRAM_DATA":     {1062207488, 1073217536},
		"RTC_DRAM":        {1073340416, 1073348608},
		"BYTE_ACCESSIBLE": {1073340416, 1073741824},
		"MEM_INTERNAL":    {1073340416, 1074208768},
		"DRAM":            {1073414144, 1073741824},
		"IROM_MASK":       {1073741824, 1073848576},
		"IRAM":            {1073872896, 1074200576},
		"RTC_IRAM":        {1074200576, 1074208768},
		"IROM":            {1074266112, 1082130432},
		"RTC_DATA":        {1342177280, 1342185472},
	},
}
