package core

/* This file is automatically generated */
//######################################//

var ESP32ROM = ModulStruct{
	Name: "ESP32",

	Sys: ModulSystemStruct{
		UF2:         475996592, //0x1c5f21b0
		Chip:        0,
		LenStatus:   2,
		FlashOffset: 4096,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 32,
		Supports:   false,
	},
	MagicValue: []uint64{
		15736195, //0xf01d83
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"DROM":            {1061158912, 1065353216}, //0x3f400000 0x3f800000
		"EXTRAM_DATA":     {1065353216, 1069547520}, //0x3f800000 0x3fc00000
		"RTC_DRAM":        {1073217536, 1073225728}, //0x3ff80000 0x3ff82000
		"BYTE_ACCESSIBLE": {1073283072, 1073741824}, //0x3ff90000 0x40000000
		"DRAM":            {1073405952, 1073741824}, //0x3ffae000 0x40000000
		"DIRAM_DRAM":      {1073610752, 1073741820}, //0x3ffe0000 0x3ffffffc
		"CACHE_PRO":       {1074200576, 1074233344}, //0x40070000 0x40078000
		"CACHE_APP":       {1074233344, 1074266112}, //0x40078000 0x40080000
		"IRAM":            {1074266112, 1074397184}, //0x40080000 0x400a0000
		"DIRAM_IRAM":      {1074397184, 1074528252}, //0x400a0000 0x400bfffc
		"RTC_IRAM":        {1074528256, 1074536448}, //0x400c0000 0x400c2000
		"IROM":            {1074593792, 1077936128}, //0x400d0000 0x40400000
		"RTC_DATA":        {1342177280, 1342185472}, //0x50000000 0x50002000
	},
}
