package core

/* This file is automatically generated */

var ESP32C3ROM = ModulStruct{
	Name: "ESP32-C3",

	Sys: ModulSystemStruct{
		UF2:         3559628908, //0xd42ba06c
		Chip:        5,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{
		1763790959, //0x6921506f
		456216687,  //0x1b31506f
		1216438383, //0x4881606f
		1130455151, //0x4361606f
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"DROM":            {1006632960, 1015021568}, //0x3c000000 0x3c800000
		"DRAM":            {1070071808, 1070465024}, //0x3fc80000 0x3fce0000
		"BYTE_ACCESSIBLE": {1070104576, 1070596096}, //0x3fc88000 0x3fd00000
		"DROM_MASK":       {1072693248, 1072824320}, //0x3ff00000 0x3ff20000
		"IROM_MASK":       {1073741824, 1074135040}, //0x40000000 0x40060000
		"IRAM":            {1077395456, 1077805056}, //0x4037c000 0x403e0000
		"IROM":            {1107296256, 1115684864}, //0x42000000 0x42800000
		"RTC_DRAM":        {1342177280, 1342185472}, //0x50000000 0x50002000
		"RTC_IRAM":        {1342177280, 1342185472}, //0x50000000 0x50002000
		"MEM_INTERNAL2":   {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
