package core

/* This file is automatically generated */
//######################################//

var ESP32C6ROM = ModulStruct{
	Name: "ESP32-C6",

	Sys: ModulSystemStruct{
		UF2:         1410195298,
		Chip:        13,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{752910447},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"IROM_MASK":       {1073741824, 1074048000},
		"DROM_MASK":       {1074048000, 1074069504},
		"BYTE_ACCESSIBLE": {1082130432, 1082654720},
		"DRAM":            {1082130432, 1082654720},
		"IRAM":            {1082130432, 1082654720},
		"IROM":            {1107296256, 1115684864},
		"DROM":            {1115684864, 1124073472},
		"RTC_DRAM":        {1342177280, 1342193664},
		"RTC_IRAM":        {1342177280, 1342193664},
		"MEM_INTERNAL2":   {1611653120, 1611661312},
	},
}
