package core

/* This file is automatically generated */

var ESP32H2ROM = ModulStruct{
	Name: "ESP32-H2",

	Sys: ModulSystemStruct{
		UF2:         858203894, //0x332726f6
		Chip:        16,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{
		3619110528, //0xd7b73e80
	},
	Memory: map[string]ModulMapStruct{},
}
