package core

/* This file is automatically generated */
//######################################//

var ESP32C3ROM = ModulStruct{
	Name: "ESP32-C3",

	Sys: ModulSystemStruct{
		UF2:         3559628908,
		Chip:        5,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{1763790959, 456216687, 1216438383, 1130455151},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"DROM":            {1006632960, 1015021568},
		"DRAM":            {1070071808, 1070465024},
		"BYTE_ACCESSIBLE": {1070104576, 1070596096},
		"DROM_MASK":       {1072693248, 1072824320},
		"IROM_MASK":       {1073741824, 1074135040},
		"IRAM":            {1077395456, 1077805056},
		"IROM":            {1107296256, 1115684864},
		"RTC_DRAM":        {1342177280, 1342185472},
		"RTC_IRAM":        {1342177280, 1342185472},
		"MEM_INTERNAL2":   {1611653120, 1611661312},
	},
}
