package core

/* This file is automatically generated */
//######################################//

var ESP32C5ROM = ModulStruct{
	Name: "ESP32-C5",

	Sys: ModulSystemStruct{
		UF2:         4145808195,
		Chip:        23,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{285294703},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"IROM_MASK":       {1073741824, 1073979392},
		"DROM_MASK":       {1073979392, 1074003968},
		"BYTE_ACCESSIBLE": {1082130432, 1082523648},
		"DRAM":            {1082130432, 1082523648},
		"IRAM":            {1082130432, 1082523648},
		"IROM":            {1107296256, 1115684864},
		"DROM":            {1115684864, 1124073472},
		"RTC_DRAM":        {1342177280, 1342193664},
		"RTC_IRAM":        {1342177280, 1342193664},
		"MEM_INTERNAL2":   {1611653120, 1611661312},
	},
}
