package core

/* This file is automatically generated */
//######################################//

var ESP32P4ROM = ModulStruct{
	Name: "ESP32-P4",

	Sys: ModulSystemStruct{
		UF2:         1026592404, //0x3d308e94
		Chip:        18,
		LenStatus:   2,
		FlashOffset: 8192,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{
		0,         //0x00
		182303440, //0xaddbad0
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"DROM":            {1073741824, 1275068416}, //0x40000000 0x4c000000
		"IROM":            {1073741824, 1275068416}, //0x40000000 0x4c000000
		"DROM_MASK":       {1337982976, 1338114048}, //0x4fc00000 0x4fc20000
		"IROM_MASK":       {1337982976, 1338114048}, //0x4fc00000 0x4fc20000
		"BYTE_ACCESSIBLE": {1341128704, 1341784064}, //0x4ff00000 0x4ffa0000
		"DRAM":            {1341128704, 1341784064}, //0x4ff00000 0x4ffa0000
		"IRAM":            {1341128704, 1341784064}, //0x4ff00000 0x4ffa0000
		"RTC_DRAM":        {1343258624, 1343291392}, //0x50108000 0x50110000
		"RTC_IRAM":        {1343258624, 1343291392}, //0x50108000 0x50110000
		"MEM_INTERNAL2":   {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
