package core

/* This file is automatically generated */

var ESP32C5ROM = ModulStruct{
	Name: "ESP32-C5",

	Sys: ModulSystemStruct{
		UF2:         4145808195, //0xf71c0343
		Chip:        23,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{
		285294703, //0x1101406f
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"IROM_MASK":       {1073741824, 1073979392}, //0x40000000 0x4003a000
		"DROM_MASK":       {1073979392, 1074003968}, //0x4003a000 0x40040000
		"BYTE_ACCESSIBLE": {1082130432, 1082523648}, //0x40800000 0x40860000
		"DRAM":            {1082130432, 1082523648}, //0x40800000 0x40860000
		"IRAM":            {1082130432, 1082523648}, //0x40800000 0x40860000
		"IROM":            {1107296256, 1115684864}, //0x42000000 0x42800000
		"DROM":            {1115684864, 1124073472}, //0x42800000 0x43000000
		"RTC_DRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"RTC_IRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"MEM_INTERNAL2":   {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
