package core

/* This file is automatically generated */

var ESP32S2ROM = ModulStruct{
	Name: "ESP32-S2",

	Sys: ModulSystemStruct{
		UF2:         3218951918, //0xbfdd4eee
		Chip:        2,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{
		1990, //0x7c6
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"DROM":            {1056964608, 1073217536}, //0x3f000000 0x3ff80000
		"EXTRAM_DATA":     {1062207488, 1073217536}, //0x3f500000 0x3ff80000
		"RTC_DRAM":        {1073340416, 1073348608}, //0x3ff9e000 0x3ffa0000
		"BYTE_ACCESSIBLE": {1073340416, 1073741824}, //0x3ff9e000 0x40000000
		"MEM_INTERNAL":    {1073340416, 1074208768}, //0x3ff9e000 0x40072000
		"DRAM":            {1073414144, 1073741824}, //0x3ffb0000 0x40000000
		"IROM_MASK":       {1073741824, 1073848576}, //0x40000000 0x4001a100
		"IRAM":            {1073872896, 1074200576}, //0x40020000 0x40070000
		"RTC_IRAM":        {1074200576, 1074208768}, //0x40070000 0x40072000
		"IROM":            {1074266112, 1082130432}, //0x40080000 0x40800000
		"RTC_DATA":        {1342177280, 1342185472}, //0x50000000 0x50002000
	},
}
