package core

/* This file is automatically generated */

var ESP32C61ROM = ModulStruct{
	Name: "ESP32-C61",

	Sys: ModulSystemStruct{
		UF2:         2010665156, //0x77d850c4
		Chip:        20,
		LenStatus:   0,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{
		871374959, //0x33f0206f
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"IROM_MASK":       {1073741824, 1074048000}, //0x40000000 0x4004ac00
		"DROM_MASK":       {1074048000, 1074069504}, //0x4004ac00 0x40050000
		"BYTE_ACCESSIBLE": {1082130432, 1082523648}, //0x40800000 0x40860000
		"DRAM":            {1082130432, 1082523648}, //0x40800000 0x40860000
		"IRAM":            {1082130432, 1082523648}, //0x40800000 0x40860000
		"IROM":            {1090519040, 1098907648}, //0x41000000 0x41800000
		"DROM":            {1098907648, 1107296256}, //0x41800000 0x42000000
		"RTC_DRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"RTC_IRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"MEM_INTERNAL2":   {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
