package core

/* This file is automatically generated */
//######################################//

var ESP32P4ROM = ModulStruct{
	Name: "ESP32-P4",

	Sys: ModulSystemStruct{
		UF2:         1026592404,
		Chip:        18,
		LenStatus:   2,
		FlashOffset: 8192,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{0, 182303440},
	Memory: map[string]ModulMapStruct{
		"RTC_DRAM":        {1343258624, 1343291392},
		"BYTE_ACCESSIBLE": {1341128704, 1341784064},
		"IROM_MASK":       {1337982976, 1338114048},
		"IRAM":            {1341128704, 1341784064},
		"DROM_MASK":       {1337982976, 1338114048},
		"IROM":            {1073741824, 1275068416},
		"RTC_IRAM":        {1343258624, 1343291392},
		"MEM_INTERNAL2":   {1611653120, 1611661312},
		"PADDING":         {0, 65536},
		"DROM":            {1073741824, 1275068416},
		"DRAM":            {1341128704, 1341784064},
	},
}
