package core

/* This file is automatically generated */
//######################################//

var ESP32S3ROM = ModulStruct{
	Name: "ESP32-S3",

	Sys: ModulSystemStruct{
		UF2:         3296614247, //0xc47e5767
		Chip:        9,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{
		9, //0x09
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"DROM":            {1006632960, 1023410176}, //0x3c000000 0x3d000000
		"EXTRAM_DATA":     {1023410176, 1040187392}, //0x3d000000 0x3e000000
		"BYTE_ACCESSIBLE": {1070104576, 1070596096}, //0x3fc88000 0x3fd00000
		"DRAM":            {1070104576, 1070596096}, //0x3fc88000 0x3fd00000
		"MEM_INTERNAL":    {1070104576, 1077813248}, //0x3fc88000 0x403e2000
		"IROM_MASK":       {1073741824, 1073848576}, //0x40000000 0x4001a100
		"IRAM":            {1077346304, 1077805056}, //0x40370000 0x403e0000
		"IROM":            {1107296256, 1115684864}, //0x42000000 0x42800000
		"RTC_DATA":        {1342177280, 1342185472}, //0x50000000 0x50002000
		"RTC_DRAM":        {1611653120, 1611661312}, //0x600fe000 0x60100000
		"RTC_IRAM":        {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
