package core

/* This file is automatically generated */
//######################################//

var ESP32ROM = ModulStruct{
	Name: "ESP32",

	Sys: ModulSystemStruct{
		UF2:         475996592,
		Chip:        0,
		LenStatus:   2,
		FlashOffset: 4096,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 32,
		Supports:   false,
	},
	MagicValue: []uint64{15736195},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"DROM":            {1061158912, 1065353216},
		"EXTRAM_DATA":     {1065353216, 1069547520},
		"RTC_DRAM":        {1073217536, 1073225728},
		"BYTE_ACCESSIBLE": {1073283072, 1073741824},
		"DRAM":            {1073405952, 1073741824},
		"DIRAM_DRAM":      {1073610752, 1073741820},
		"CACHE_PRO":       {1074200576, 1074233344},
		"CACHE_APP":       {1074233344, 1074266112},
		"IRAM":            {1074266112, 1074397184},
		"DIRAM_IRAM":      {1074397184, 1074528252},
		"RTC_IRAM":        {1074528256, 1074536448},
		"IROM":            {1074593792, 1077936128},
		"RTC_DATA":        {1342177280, 1342185472},
	},
}
