package core

/* This file is automatically generated */
//######################################//

var ESP32S3ROM = ModulStruct{
	Name: "ESP32-S3",

	Sys: ModulSystemStruct{
		UF2:         3296614247,
		Chip:        9,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{9},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"DROM":            {1006632960, 1023410176},
		"EXTRAM_DATA":     {1023410176, 1040187392},
		"BYTE_ACCESSIBLE": {1070104576, 1070596096},
		"DRAM":            {1070104576, 1070596096},
		"MEM_INTERNAL":    {1070104576, 1077813248},
		"IROM_MASK":       {1073741824, 1073848576},
		"IRAM":            {1077346304, 1077805056},
		"IROM":            {1107296256, 1115684864},
		"RTC_DATA":        {1342177280, 1342185472},
		"RTC_DRAM":        {1611653120, 1611661312},
		"RTC_IRAM":        {1611653120, 1611661312},
	},
}
