package core

/* This file is automatically generated */

var ESP32C6ROM = ModulStruct{
	Name: "ESP32-C6",

	Sys: ModulSystemStruct{
		UF2:         1410195298, //0x540ddf62
		Chip:        13,
		LenStatus:   2,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 16,
		Supports:   true,
	},
	MagicValue: []uint64{
		752910447, //0x2ce0806f
	},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},               //0x00 0x10000
		"IROM_MASK":       {1073741824, 1074048000}, //0x40000000 0x4004ac00
		"DROM_MASK":       {1074048000, 1074069504}, //0x4004ac00 0x40050000
		"BYTE_ACCESSIBLE": {1082130432, 1082654720}, //0x40800000 0x40880000
		"DRAM":            {1082130432, 1082654720}, //0x40800000 0x40880000
		"IRAM":            {1082130432, 1082654720}, //0x40800000 0x40880000
		"IROM":            {1107296256, 1115684864}, //0x42000000 0x42800000
		"DROM":            {1115684864, 1124073472}, //0x42800000 0x43000000
		"RTC_DRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"RTC_IRAM":        {1342177280, 1342193664}, //0x50000000 0x50004000
		"MEM_INTERNAL2":   {1611653120, 1611661312}, //0x600fe000 0x60100000
	},
}
