package core

/* This file is automatically generated */
//######################################//

var ESP32C61ROM = ModulStruct{
	Name: "ESP32-C61",

	Sys: ModulSystemStruct{
		UF2:         2010665156,
		Chip:        20,
		LenStatus:   0,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{871374959},
	Memory: map[string]ModulMapStruct{
		"PADDING":         {0, 65536},
		"IROM_MASK":       {1073741824, 1074048000},
		"DROM_MASK":       {1074048000, 1074069504},
		"BYTE_ACCESSIBLE": {1082130432, 1082523648},
		"DRAM":            {1082130432, 1082523648},
		"IRAM":            {1082130432, 1082523648},
		"IROM":            {1090519040, 1098907648},
		"DROM":            {1098907648, 1107296256},
		"RTC_DRAM":        {1342177280, 1342193664},
		"RTC_IRAM":        {1342177280, 1342193664},
		"MEM_INTERNAL2":   {1611653120, 1611661312},
	},
}
