package core

/* This file is automatically generated */
//######################################//

var ESP8266ROM = ModulStruct{
	Name: "ESP8266",

	Sys: ModulSystemStruct{
		UF2:         2125160941,
		Chip:        0,
		LenStatus:   0,
		FlashOffset: 0,
	},
	Encrypt: ModulEncryptStruct{
		WriteAlign: 0,
		Supports:   false,
	},
	MagicValue: []uint64{4293968129},
	Memory: map[string]ModulMapStruct{
		"DPORT": {1072693248, 1072693264},
		"DRAM":  {1073643520, 1073741824},
		"IRAM":  {1074790400, 1074823168},
		"IROM":  {1075843088, 1076760592},
	},
}
