package core

/* This file is automatically generated */

var EspList = []*ModulStruct{
	&ESP8266ROM,
	&ESP32S2ROM,
	&ESP32C61ROM,
	&ESP32C6ROM,
	&ESP32H2ROM,
	&ESP32ROM,
	&ESP32C3ROM,
	&ESP32C5ROM,
	&ESP32S3ROM,
	&ESP32C2ROM,
	&ESP32P4ROM,
}
