package address

/* This file is automatically generated */

type PeripheralType byte

const (
	DPortRegister   PeripheralType = 2  //4 KB
	AESAccelerator  PeripheralType = 3  //4 KB
	RSAAccelerator  PeripheralType = 4  //4 KB
	SHAAccelerator  PeripheralType = 5  //4 KB
	SecureBoot      PeripheralType = 6  //4 KB
	CacheMMUTable   PeripheralType = 7  //16 KB
	PIDController   PeripheralType = 8  //4 KB		Per-CPU peripheral
	UART0           PeripheralType = 9  //4 KB
	SPI1            PeripheralType = 10 //4 KB
	SPI0            PeripheralType = 11 //4 KB
	GPIO            PeripheralType = 12 //4 KB
	RTC             PeripheralType = 13 //4 KB
	IOMUX           PeripheralType = 14 //4 KB
	SDIOSlave1      PeripheralType = 15 //4 KB		One of three parts
	UDMA1           PeripheralType = 16 //4 KB
	I2S0            PeripheralType = 17 //4 KB
	UART1           PeripheralType = 18 //4 KB
	I2C0            PeripheralType = 19 //4 KB
	UDMA0           PeripheralType = 20 //4 KB
	SDIOSlave2      PeripheralType = 21 //4 KB		One of three parts
	RMT             PeripheralType = 22 //4 KB
	PCNT            PeripheralType = 23 //4 KB
	SDIOSlave3      PeripheralType = 24 //4 KB		One of three parts
	LEDPWM          PeripheralType = 25 //4 KB
	EFuseController PeripheralType = 26 //4 KB
	FlashEncryption PeripheralType = 27 //4 KB
	MCPWM0          PeripheralType = 28 //4 KB
	TIMG0           PeripheralType = 29 //4 KB
	TIMG1           PeripheralType = 30 //4 KB
	SPI2            PeripheralType = 31 //4 KB
	SPI3            PeripheralType = 32 //4 KB
	SYSCON          PeripheralType = 33 //4 KB
	I2C1            PeripheralType = 34 //4 KB
	SDMMC           PeripheralType = 35 //4 KB
	EMAC            PeripheralType = 36 //8 KB
	TWAI            PeripheralType = 37 //4KB
	MCPWM1          PeripheralType = 38 //4 KB
	I2S1            PeripheralType = 39 //4 KB
	UART2           PeripheralType = 40 //4 KB
	RNG             PeripheralType = 43 //4 KB
)

const (
	AdrBeginDPortRegister   AddressType = 0x3FF0_0000
	AdrBeginAESAccelerator  AddressType = 0x3FF0_1000
	AdrBeginRSAAccelerator  AddressType = 0x3FF0_2000
	AdrBeginSHAAccelerator  AddressType = 0x3FF0_3000
	AdrBeginSecureBoot      AddressType = 0x3FF0_4000
	AdrBeginCacheMMUTable   AddressType = 0x3FF1_0000
	AdrBeginPIDController   AddressType = 0x3FF1_F000
	AdrBeginUART0           AddressType = 0x3FF4_0000
	AdrBeginSPI1            AddressType = 0x3FF4_2000
	AdrBeginSPI0            AddressType = 0x3FF4_3000
	AdrBeginGPIO            AddressType = 0x3FF4_4000
	AdrBeginRTC             AddressType = 0x3FF4_8000
	AdrBeginIOMUX           AddressType = 0x3FF4_9000
	AdrBeginSDIOSlave1      AddressType = 0x3FF4_B000
	AdrBeginUDMA1           AddressType = 0x3FF4_C000
	AdrBeginI2S0            AddressType = 0x3FF4_F000
	AdrBeginUART1           AddressType = 0x3FF5_0000
	AdrBeginI2C0            AddressType = 0x3FF5_3000
	AdrBeginUDMA0           AddressType = 0x3FF5_4000
	AdrBeginSDIOSlave2      AddressType = 0x3FF5_5000
	AdrBeginRMT             AddressType = 0x3FF5_6000
	AdrBeginPCNT            AddressType = 0x3FF5_7000
	AdrBeginSDIOSlave3      AddressType = 0x3FF5_8000
	AdrBeginLEDPWM          AddressType = 0x3FF5_9000
	AdrBeginEFuseController AddressType = 0x3FF5_A000
	AdrBeginFlashEncryption AddressType = 0x3FF5_B000
	AdrBeginMCPWM0          AddressType = 0x3FF5_E000
	AdrBeginTIMG0           AddressType = 0x3FF5_F000
	AdrBeginTIMG1           AddressType = 0x3FF6_0000
	AdrBeginSPI2            AddressType = 0x3FF6_4000
	AdrBeginSPI3            AddressType = 0x3FF6_5000
	AdrBeginSYSCON          AddressType = 0x3FF6_6000
	AdrBeginI2C1            AddressType = 0x3FF6_7000
	AdrBeginSDMMC           AddressType = 0x3FF6_8000
	AdrBeginEMAC            AddressType = 0x3FF6_9000
	AdrBeginTWAI            AddressType = 0x3FF6_B000
	AdrBeginMCPWM1          AddressType = 0x3FF6_C000
	AdrBeginI2S1            AddressType = 0x3FF6_D000
	AdrBeginUART2           AddressType = 0x3FF6_E000
	AdrBeginRNG             AddressType = 0x3FF7_5000
)

const (
	AdrEndDPortRegister   AddressType = 0x3FF0_0FFF
	AdrEndAESAccelerator  AddressType = 0x3FF0_1FFF
	AdrEndRSAAccelerator  AddressType = 0x3FF0_2FFF
	AdrEndSHAAccelerator  AddressType = 0x3FF0_3FFF
	AdrEndSecureBoot      AddressType = 0x3FF0_4FFF
	AdrEndCacheMMUTable   AddressType = 0x3FF1_3FFF
	AdrEndPIDController   AddressType = 0x3FF1_FFFF
	AdrEndUART0           AddressType = 0x3FF4_0FFF
	AdrEndSPI1            AddressType = 0x3FF4_2FFF
	AdrEndSPI0            AddressType = 0x3FF4_3FFF
	AdrEndGPIO            AddressType = 0x3FF4_4FFF
	AdrEndRTC             AddressType = 0x3FF4_8FFF
	AdrEndIOMUX           AddressType = 0x3FF4_9FFF
	AdrEndSDIOSlave1      AddressType = 0x3FF4_BFFF
	AdrEndUDMA1           AddressType = 0x3FF4_CFFF
	AdrEndI2S0            AddressType = 0x3FF4_FFFF
	AdrEndUART1           AddressType = 0x3FF5_0FFF
	AdrEndI2C0            AddressType = 0x3FF5_3FFF
	AdrEndUDMA0           AddressType = 0x3FF5_4FFF
	AdrEndSDIOSlave2      AddressType = 0x3FF5_5FFF
	AdrEndRMT             AddressType = 0x3FF5_6FFF
	AdrEndPCNT            AddressType = 0x3FF5_7FFF
	AdrEndSDIOSlave3      AddressType = 0x3FF5_8FFF
	AdrEndLEDPWM          AddressType = 0x3FF5_9FFF
	AdrEndEFuseController AddressType = 0x3FF5_AFFF
	AdrEndFlashEncryption AddressType = 0x3FF5_BFFF
	AdrEndMCPWM0          AddressType = 0x3FF5_EFFF
	AdrEndTIMG0           AddressType = 0x3FF5_FFFF
	AdrEndTIMG1           AddressType = 0x3FF6_0FFF
	AdrEndSPI2            AddressType = 0x3FF6_4FFF
	AdrEndSPI3            AddressType = 0x3FF6_5FFF
	AdrEndSYSCON          AddressType = 0x3FF6_6FFF
	AdrEndI2C1            AddressType = 0x3FF6_7FFF
	AdrEndSDMMC           AddressType = 0x3FF6_8FFF
	AdrEndEMAC            AddressType = 0x3FF6_AFFF
	AdrEndTWAI            AddressType = 0x3FF6_BFFF
	AdrEndMCPWM1          AddressType = 0x3FF6_CFFF
	AdrEndI2S1            AddressType = 0x3FF6_DFFF
	AdrEndUART2           AddressType = 0x3FF6_EFFF
	AdrEndRNG             AddressType = 0x3FF7_5FFF
)

var (
	AdrDPortRegister   = AddressCellObj{AdrBeginDPortRegister, AdrEndDPortRegister}     //4 KB
	AdrAESAccelerator  = AddressCellObj{AdrBeginAESAccelerator, AdrEndAESAccelerator}   //4 KB
	AdrRSAAccelerator  = AddressCellObj{AdrBeginRSAAccelerator, AdrEndRSAAccelerator}   //4 KB
	AdrSHAAccelerator  = AddressCellObj{AdrBeginSHAAccelerator, AdrEndSHAAccelerator}   //4 KB
	AdrSecureBoot      = AddressCellObj{AdrBeginSecureBoot, AdrEndSecureBoot}           //4 KB
	AdrCacheMMUTable   = AddressCellObj{AdrBeginCacheMMUTable, AdrEndCacheMMUTable}     //16 KB
	AdrPIDController   = AddressCellObj{AdrBeginPIDController, AdrEndPIDController}     //4 KB		Per-CPU peripheral
	AdrUART0           = AddressCellObj{AdrBeginUART0, AdrEndUART0}                     //4 KB
	AdrSPI1            = AddressCellObj{AdrBeginSPI1, AdrEndSPI1}                       //4 KB
	AdrSPI0            = AddressCellObj{AdrBeginSPI0, AdrEndSPI0}                       //4 KB
	AdrGPIO            = AddressCellObj{AdrBeginGPIO, AdrEndGPIO}                       //4 KB
	AdrRTC             = AddressCellObj{AdrBeginRTC, AdrEndRTC}                         //4 KB
	AdrIOMUX           = AddressCellObj{AdrBeginIOMUX, AdrEndIOMUX}                     //4 KB
	AdrSDIOSlave1      = AddressCellObj{AdrBeginSDIOSlave1, AdrEndSDIOSlave1}           //4 KB		One of three parts
	AdrUDMA1           = AddressCellObj{AdrBeginUDMA1, AdrEndUDMA1}                     //4 KB
	AdrI2S0            = AddressCellObj{AdrBeginI2S0, AdrEndI2S0}                       //4 KB
	AdrUART1           = AddressCellObj{AdrBeginUART1, AdrEndUART1}                     //4 KB
	AdrI2C0            = AddressCellObj{AdrBeginI2C0, AdrEndI2C0}                       //4 KB
	AdrUDMA0           = AddressCellObj{AdrBeginUDMA0, AdrEndUDMA0}                     //4 KB
	AdrSDIOSlave2      = AddressCellObj{AdrBeginSDIOSlave2, AdrEndSDIOSlave2}           //4 KB		One of three parts
	AdrRMT             = AddressCellObj{AdrBeginRMT, AdrEndRMT}                         //4 KB
	AdrPCNT            = AddressCellObj{AdrBeginPCNT, AdrEndPCNT}                       //4 KB
	AdrSDIOSlave3      = AddressCellObj{AdrBeginSDIOSlave3, AdrEndSDIOSlave3}           //4 KB		One of three parts
	AdrLEDPWM          = AddressCellObj{AdrBeginLEDPWM, AdrEndLEDPWM}                   //4 KB
	AdrEFuseController = AddressCellObj{AdrBeginEFuseController, AdrEndEFuseController} //4 KB
	AdrFlashEncryption = AddressCellObj{AdrBeginFlashEncryption, AdrEndFlashEncryption} //4 KB
	AdrMCPWM0          = AddressCellObj{AdrBeginMCPWM0, AdrEndMCPWM0}                   //4 KB
	AdrTIMG0           = AddressCellObj{AdrBeginTIMG0, AdrEndTIMG0}                     //4 KB
	AdrTIMG1           = AddressCellObj{AdrBeginTIMG1, AdrEndTIMG1}                     //4 KB
	AdrSPI2            = AddressCellObj{AdrBeginSPI2, AdrEndSPI2}                       //4 KB
	AdrSPI3            = AddressCellObj{AdrBeginSPI3, AdrEndSPI3}                       //4 KB
	AdrSYSCON          = AddressCellObj{AdrBeginSYSCON, AdrEndSYSCON}                   //4 KB
	AdrI2C1            = AddressCellObj{AdrBeginI2C1, AdrEndI2C1}                       //4 KB
	AdrSDMMC           = AddressCellObj{AdrBeginSDMMC, AdrEndSDMMC}                     //4 KB
	AdrEMAC            = AddressCellObj{AdrBeginEMAC, AdrEndEMAC}                       //8 KB
	AdrTWAI            = AddressCellObj{AdrBeginTWAI, AdrEndTWAI}                       //4KB
	AdrMCPWM1          = AddressCellObj{AdrBeginMCPWM1, AdrEndMCPWM1}                   //4 KB
	AdrI2S1            = AddressCellObj{AdrBeginI2S1, AdrEndI2S1}                       //4 KB
	AdrUART2           = AddressCellObj{AdrBeginUART2, AdrEndUART2}                     //4 KB
	AdrRNG             = AddressCellObj{AdrBeginRNG, AdrEndRNG}                         //4 KB
)

var PeripheralMap = map[PeripheralType]*AddressCellObj{
	DPortRegister:   &AdrDPortRegister,
	AESAccelerator:  &AdrAESAccelerator,
	RSAAccelerator:  &AdrRSAAccelerator,
	SHAAccelerator:  &AdrSHAAccelerator,
	SecureBoot:      &AdrSecureBoot,
	CacheMMUTable:   &AdrCacheMMUTable,
	PIDController:   &AdrPIDController,
	UART0:           &AdrUART0,
	SPI1:            &AdrSPI1,
	SPI0:            &AdrSPI0,
	GPIO:            &AdrGPIO,
	RTC:             &AdrRTC,
	IOMUX:           &AdrIOMUX,
	SDIOSlave1:      &AdrSDIOSlave1,
	UDMA1:           &AdrUDMA1,
	I2S0:            &AdrI2S0,
	UART1:           &AdrUART1,
	I2C0:            &AdrI2C0,
	UDMA0:           &AdrUDMA0,
	SDIOSlave2:      &AdrSDIOSlave2,
	RMT:             &AdrRMT,
	PCNT:            &AdrPCNT,
	SDIOSlave3:      &AdrSDIOSlave3,
	LEDPWM:          &AdrLEDPWM,
	EFuseController: &AdrEFuseController,
	FlashEncryption: &AdrFlashEncryption,
	MCPWM0:          &AdrMCPWM0,
	TIMG0:           &AdrTIMG0,
	TIMG1:           &AdrTIMG1,
	SPI2:            &AdrSPI2,
	SPI3:            &AdrSPI3,
	SYSCON:          &AdrSYSCON,
	I2C1:            &AdrI2C1,
	SDMMC:           &AdrSDMMC,
	EMAC:            &AdrEMAC,
	TWAI:            &AdrTWAI,
	MCPWM1:          &AdrMCPWM1,
	I2S1:            &AdrI2S1,
	UART2:           &AdrUART2,
	RNG:             &AdrRNG,
}
