package address

/* This file is automatically generated */

type PerType byte

const (
	PerDPortRegister   PerType = 2  //4 KB
	PerAESAccelerator  PerType = 3  //4 KB
	PerRSAAccelerator  PerType = 4  //4 KB
	PerSHAAccelerator  PerType = 5  //4 KB
	PerSecureBoot      PerType = 6  //4 KB
	PerCacheMMUTable   PerType = 7  //16 KB
	PerPIDController   PerType = 8  //4 KB		Per-CPU peripheral
	PerUART0           PerType = 9  //4 KB
	PerSPI1            PerType = 10 //4 KB
	PerSPI0            PerType = 11 //4 KB
	PerGPIO            PerType = 12 //4 KB
	PerRTC             PerType = 13 //4 KB
	PerIOMUX           PerType = 14 //4 KB
	PerSDIOSlave1      PerType = 15 //4 KB		One of three parts
	PerUDMA1           PerType = 16 //4 KB
	PerI2S0            PerType = 17 //4 KB
	PerUART1           PerType = 18 //4 KB
	PerI2C0            PerType = 19 //4 KB
	PerUDMA0           PerType = 20 //4 KB
	PerSDIOSlave2      PerType = 21 //4 KB		One of three parts
	PerRMT             PerType = 22 //4 KB
	PerPCNT            PerType = 23 //4 KB
	PerSDIOSlave3      PerType = 24 //4 KB		One of three parts
	PerLEDPWM          PerType = 25 //4 KB
	PerEFuseController PerType = 26 //4 KB
	PerFlashEncryption PerType = 27 //4 KB
	PerMCPWM0          PerType = 28 //4 KB
	PerTIMG0           PerType = 29 //4 KB
	PerTIMG1           PerType = 30 //4 KB
	PerSPI2            PerType = 31 //4 KB
	PerSPI3            PerType = 32 //4 KB
	PerSYSCON          PerType = 33 //4 KB
	PerI2C1            PerType = 34 //4 KB
	PerSDMMC           PerType = 35 //4 KB
	PerEMAC            PerType = 36 //8 KB
	PerTWAI            PerType = 37 //4KB
	PerMCPWM1          PerType = 38 //4 KB
	PerI2S1            PerType = 39 //4 KB
	PerUART2           PerType = 40 //4 KB
	PerRNG             PerType = 43 //4 KB
)

const (
	PerAdrBeginDPortRegister   AddressType = 0x3FF0_0000
	PerAdrBeginAESAccelerator  AddressType = 0x3FF0_1000
	PerAdrBeginRSAAccelerator  AddressType = 0x3FF0_2000
	PerAdrBeginSHAAccelerator  AddressType = 0x3FF0_3000
	PerAdrBeginSecureBoot      AddressType = 0x3FF0_4000
	PerAdrBeginCacheMMUTable   AddressType = 0x3FF1_0000
	PerAdrBeginPIDController   AddressType = 0x3FF1_F000
	PerAdrBeginUART0           AddressType = 0x3FF4_0000
	PerAdrBeginSPI1            AddressType = 0x3FF4_2000
	PerAdrBeginSPI0            AddressType = 0x3FF4_3000
	PerAdrBeginGPIO            AddressType = 0x3FF4_4000
	PerAdrBeginRTC             AddressType = 0x3FF4_8000
	PerAdrBeginIOMUX           AddressType = 0x3FF4_9000
	PerAdrBeginSDIOSlave1      AddressType = 0x3FF4_B000
	PerAdrBeginUDMA1           AddressType = 0x3FF4_C000
	PerAdrBeginI2S0            AddressType = 0x3FF4_F000
	PerAdrBeginUART1           AddressType = 0x3FF5_0000
	PerAdrBeginI2C0            AddressType = 0x3FF5_3000
	PerAdrBeginUDMA0           AddressType = 0x3FF5_4000
	PerAdrBeginSDIOSlave2      AddressType = 0x3FF5_5000
	PerAdrBeginRMT             AddressType = 0x3FF5_6000
	PerAdrBeginPCNT            AddressType = 0x3FF5_7000
	PerAdrBeginSDIOSlave3      AddressType = 0x3FF5_8000
	PerAdrBeginLEDPWM          AddressType = 0x3FF5_9000
	PerAdrBeginEFuseController AddressType = 0x3FF5_A000
	PerAdrBeginFlashEncryption AddressType = 0x3FF5_B000
	PerAdrBeginMCPWM0          AddressType = 0x3FF5_E000
	PerAdrBeginTIMG0           AddressType = 0x3FF5_F000
	PerAdrBeginTIMG1           AddressType = 0x3FF6_0000
	PerAdrBeginSPI2            AddressType = 0x3FF6_4000
	PerAdrBeginSPI3            AddressType = 0x3FF6_5000
	PerAdrBeginSYSCON          AddressType = 0x3FF6_6000
	PerAdrBeginI2C1            AddressType = 0x3FF6_7000
	PerAdrBeginSDMMC           AddressType = 0x3FF6_8000
	PerAdrBeginEMAC            AddressType = 0x3FF6_9000
	PerAdrBeginTWAI            AddressType = 0x3FF6_B000
	PerAdrBeginMCPWM1          AddressType = 0x3FF6_C000
	PerAdrBeginI2S1            AddressType = 0x3FF6_D000
	PerAdrBeginUART2           AddressType = 0x3FF6_E000
	PerAdrBeginRNG             AddressType = 0x3FF7_5000
)

const (
	PerAdrEndDPortRegister   AddressType = 0x3FF0_0FFF
	PerAdrEndAESAccelerator  AddressType = 0x3FF0_1FFF
	PerAdrEndRSAAccelerator  AddressType = 0x3FF0_2FFF
	PerAdrEndSHAAccelerator  AddressType = 0x3FF0_3FFF
	PerAdrEndSecureBoot      AddressType = 0x3FF0_4FFF
	PerAdrEndCacheMMUTable   AddressType = 0x3FF1_3FFF
	PerAdrEndPIDController   AddressType = 0x3FF1_FFFF
	PerAdrEndUART0           AddressType = 0x3FF4_0FFF
	PerAdrEndSPI1            AddressType = 0x3FF4_2FFF
	PerAdrEndSPI0            AddressType = 0x3FF4_3FFF
	PerAdrEndGPIO            AddressType = 0x3FF4_4FFF
	PerAdrEndRTC             AddressType = 0x3FF4_8FFF
	PerAdrEndIOMUX           AddressType = 0x3FF4_9FFF
	PerAdrEndSDIOSlave1      AddressType = 0x3FF4_BFFF
	PerAdrEndUDMA1           AddressType = 0x3FF4_CFFF
	PerAdrEndI2S0            AddressType = 0x3FF4_FFFF
	PerAdrEndUART1           AddressType = 0x3FF5_0FFF
	PerAdrEndI2C0            AddressType = 0x3FF5_3FFF
	PerAdrEndUDMA0           AddressType = 0x3FF5_4FFF
	PerAdrEndSDIOSlave2      AddressType = 0x3FF5_5FFF
	PerAdrEndRMT             AddressType = 0x3FF5_6FFF
	PerAdrEndPCNT            AddressType = 0x3FF5_7FFF
	PerAdrEndSDIOSlave3      AddressType = 0x3FF5_8FFF
	PerAdrEndLEDPWM          AddressType = 0x3FF5_9FFF
	PerAdrEndEFuseController AddressType = 0x3FF5_AFFF
	PerAdrEndFlashEncryption AddressType = 0x3FF5_BFFF
	PerAdrEndMCPWM0          AddressType = 0x3FF5_EFFF
	PerAdrEndTIMG0           AddressType = 0x3FF5_FFFF
	PerAdrEndTIMG1           AddressType = 0x3FF6_0FFF
	PerAdrEndSPI2            AddressType = 0x3FF6_4FFF
	PerAdrEndSPI3            AddressType = 0x3FF6_5FFF
	PerAdrEndSYSCON          AddressType = 0x3FF6_6FFF
	PerAdrEndI2C1            AddressType = 0x3FF6_7FFF
	PerAdrEndSDMMC           AddressType = 0x3FF6_8FFF
	PerAdrEndEMAC            AddressType = 0x3FF6_AFFF
	PerAdrEndTWAI            AddressType = 0x3FF6_BFFF
	PerAdrEndMCPWM1          AddressType = 0x3FF6_CFFF
	PerAdrEndI2S1            AddressType = 0x3FF6_DFFF
	PerAdrEndUART2           AddressType = 0x3FF6_EFFF
	PerAdrEndRNG             AddressType = 0x3FF7_5FFF
)

var (
	PerAdrDPortRegister   = AddressCellObj{PerAdrBeginDPortRegister, PerAdrEndDPortRegister}
	PerAdrAESAccelerator  = AddressCellObj{PerAdrBeginAESAccelerator, PerAdrEndAESAccelerator}
	PerAdrRSAAccelerator  = AddressCellObj{PerAdrBeginRSAAccelerator, PerAdrEndRSAAccelerator}
	PerAdrSHAAccelerator  = AddressCellObj{PerAdrBeginSHAAccelerator, PerAdrEndSHAAccelerator}
	PerAdrSecureBoot      = AddressCellObj{PerAdrBeginSecureBoot, PerAdrEndSecureBoot}
	PerAdrCacheMMUTable   = AddressCellObj{PerAdrBeginCacheMMUTable, PerAdrEndCacheMMUTable}
	PerAdrPIDController   = AddressCellObj{PerAdrBeginPIDController, PerAdrEndPIDController}
	PerAdrUART0           = AddressCellObj{PerAdrBeginUART0, PerAdrEndUART0}
	PerAdrSPI1            = AddressCellObj{PerAdrBeginSPI1, PerAdrEndSPI1}
	PerAdrSPI0            = AddressCellObj{PerAdrBeginSPI0, PerAdrEndSPI0}
	PerAdrGPIO            = AddressCellObj{PerAdrBeginGPIO, PerAdrEndGPIO}
	PerAdrRTC             = AddressCellObj{PerAdrBeginRTC, PerAdrEndRTC}
	PerAdrIOMUX           = AddressCellObj{PerAdrBeginIOMUX, PerAdrEndIOMUX}
	PerAdrSDIOSlave1      = AddressCellObj{PerAdrBeginSDIOSlave1, PerAdrEndSDIOSlave1}
	PerAdrUDMA1           = AddressCellObj{PerAdrBeginUDMA1, PerAdrEndUDMA1}
	PerAdrI2S0            = AddressCellObj{PerAdrBeginI2S0, PerAdrEndI2S0}
	PerAdrUART1           = AddressCellObj{PerAdrBeginUART1, PerAdrEndUART1}
	PerAdrI2C0            = AddressCellObj{PerAdrBeginI2C0, PerAdrEndI2C0}
	PerAdrUDMA0           = AddressCellObj{PerAdrBeginUDMA0, PerAdrEndUDMA0}
	PerAdrSDIOSlave2      = AddressCellObj{PerAdrBeginSDIOSlave2, PerAdrEndSDIOSlave2}
	PerAdrRMT             = AddressCellObj{PerAdrBeginRMT, PerAdrEndRMT}
	PerAdrPCNT            = AddressCellObj{PerAdrBeginPCNT, PerAdrEndPCNT}
	PerAdrSDIOSlave3      = AddressCellObj{PerAdrBeginSDIOSlave3, PerAdrEndSDIOSlave3}
	PerAdrLEDPWM          = AddressCellObj{PerAdrBeginLEDPWM, PerAdrEndLEDPWM}
	PerAdrEFuseController = AddressCellObj{PerAdrBeginEFuseController, PerAdrEndEFuseController}
	PerAdrFlashEncryption = AddressCellObj{PerAdrBeginFlashEncryption, PerAdrEndFlashEncryption}
	PerAdrMCPWM0          = AddressCellObj{PerAdrBeginMCPWM0, PerAdrEndMCPWM0}
	PerAdrTIMG0           = AddressCellObj{PerAdrBeginTIMG0, PerAdrEndTIMG0}
	PerAdrTIMG1           = AddressCellObj{PerAdrBeginTIMG1, PerAdrEndTIMG1}
	PerAdrSPI2            = AddressCellObj{PerAdrBeginSPI2, PerAdrEndSPI2}
	PerAdrSPI3            = AddressCellObj{PerAdrBeginSPI3, PerAdrEndSPI3}
	PerAdrSYSCON          = AddressCellObj{PerAdrBeginSYSCON, PerAdrEndSYSCON}
	PerAdrI2C1            = AddressCellObj{PerAdrBeginI2C1, PerAdrEndI2C1}
	PerAdrSDMMC           = AddressCellObj{PerAdrBeginSDMMC, PerAdrEndSDMMC}
	PerAdrEMAC            = AddressCellObj{PerAdrBeginEMAC, PerAdrEndEMAC}
	PerAdrTWAI            = AddressCellObj{PerAdrBeginTWAI, PerAdrEndTWAI}
	PerAdrMCPWM1          = AddressCellObj{PerAdrBeginMCPWM1, PerAdrEndMCPWM1}
	PerAdrI2S1            = AddressCellObj{PerAdrBeginI2S1, PerAdrEndI2S1}
	PerAdrUART2           = AddressCellObj{PerAdrBeginUART2, PerAdrEndUART2}
	PerAdrRNG             = AddressCellObj{PerAdrBeginRNG, PerAdrEndRNG}
)

var PerMap = map[PerType]*AddressCellObj{
	PerDPortRegister:   &PerAdrDPortRegister,
	PerAESAccelerator:  &PerAdrAESAccelerator,
	PerRSAAccelerator:  &PerAdrRSAAccelerator,
	PerSHAAccelerator:  &PerAdrSHAAccelerator,
	PerSecureBoot:      &PerAdrSecureBoot,
	PerCacheMMUTable:   &PerAdrCacheMMUTable,
	PerPIDController:   &PerAdrPIDController,
	PerUART0:           &PerAdrUART0,
	PerSPI1:            &PerAdrSPI1,
	PerSPI0:            &PerAdrSPI0,
	PerGPIO:            &PerAdrGPIO,
	PerRTC:             &PerAdrRTC,
	PerIOMUX:           &PerAdrIOMUX,
	PerSDIOSlave1:      &PerAdrSDIOSlave1,
	PerUDMA1:           &PerAdrUDMA1,
	PerI2S0:            &PerAdrI2S0,
	PerUART1:           &PerAdrUART1,
	PerI2C0:            &PerAdrI2C0,
	PerUDMA0:           &PerAdrUDMA0,
	PerSDIOSlave2:      &PerAdrSDIOSlave2,
	PerRMT:             &PerAdrRMT,
	PerPCNT:            &PerAdrPCNT,
	PerSDIOSlave3:      &PerAdrSDIOSlave3,
	PerLEDPWM:          &PerAdrLEDPWM,
	PerEFuseController: &PerAdrEFuseController,
	PerFlashEncryption: &PerAdrFlashEncryption,
	PerMCPWM0:          &PerAdrMCPWM0,
	PerTIMG0:           &PerAdrTIMG0,
	PerTIMG1:           &PerAdrTIMG1,
	PerSPI2:            &PerAdrSPI2,
	PerSPI3:            &PerAdrSPI3,
	PerSYSCON:          &PerAdrSYSCON,
	PerI2C1:            &PerAdrI2C1,
	PerSDMMC:           &PerAdrSDMMC,
	PerEMAC:            &PerAdrEMAC,
	PerTWAI:            &PerAdrTWAI,
	PerMCPWM1:          &PerAdrMCPWM1,
	PerI2S1:            &PerAdrI2S1,
	PerUART2:           &PerAdrUART2,
	PerRNG:             &PerAdrRNG,
}
