package main

/* This file is automatically generated */

const (
	CliValPort         = "port"
	CliValBaudConnect  = "baudConnect"
	CliValBaudTransfer = "baudTransfer"

	CliValConnTimeout = "connTimeout"
	CliValConnRetries = "connRetries"

	CliValFlashCompress = "flashCompress"
	CliValFlashOffset   = "flashOffset"
	CliValFlashSize     = "flashSize"
	CliValFlashFile     = "flashFile"
)

const (
	CliValTextPort         = "Device name or path"
	CliValTextBaudConnect  = "Serial signalling rate during connect phase"
	CliValTextBaudTransfer = "Serial signalling rate during data transfer"

	CliValTextConnTimeout = "Timeout to wait for chip response upon connecting"
	CliValTextConnRetries = "How often to retry connecting"

	CliValTextFlashCompress = "Use compression for transfer"
	CliValTextFlashOffset   = "The point where we start"
	CliValTextFlashSize     = "How many bytes do we capture?"
	CliValTextFlashFile     = "File path"
)
