package main

import "flag"

/* This file is automatically generated */

const (
	CliTrigHelp    = "help"
	CliTrigVersion = "version"

	CliTrigJson    = "json"
	CliTrigNoColor = "noColor"

	CliTrigList       = "list"
	CliTrigInfo       = "info"
	CliTrigFlashRead  = "flashRead"
	CliTrigFlashWrite = "flashWrite"
)

const (
	CliTrigTextHelp    = "Show a help page"
	CliTrigTextVersion = "Show application build information"

	CliTrigTextJson    = "Output responses in json"
	CliTrigTextNoColor = "Display output without colorization"

	CliTrigTextList       = "Get a list of available COM devices"
	CliTrigTextInfo       = "Show ESP information"
	CliTrigTextFlashRead  = "Reading firmware from ESP to file"
	CliTrigTextFlashWrite = "Recording firmware from a file in ESP"
)

type CliTrigTypeObj struct {
	Help    *bool
	Version *bool

	Json    *bool
	NoColor *bool

	List       *bool
	Info       *bool
	FlashRead  *bool
	FlashWrite *bool
}

var CliTrigType = CliTrigTypeObj{
	Help:       flag.Bool(CliTrigHelp, false, CliTrigTextHelp),
	Version:    flag.Bool(CliTrigVersion, false, CliTrigTextVersion),
	Json:       flag.Bool(CliTrigJson, false, CliTrigTextJson),
	NoColor:    flag.Bool(CliTrigNoColor, false, CliTrigTextNoColor),
	List:       flag.Bool(CliTrigList, false, CliTrigTextList),
	Info:       flag.Bool(CliTrigInfo, false, CliTrigTextInfo),
	FlashRead:  flag.Bool(CliTrigFlashRead, false, CliTrigTextFlashRead),
	FlashWrite: flag.Bool(CliTrigFlashWrite, false, CliTrigTextFlashWrite),
}

var CliTrigTypeMap = map[string]*bool{
	CliTrigHelp:       CliTrigType.Help,
	CliTrigVersion:    CliTrigType.Version,
	CliTrigJson:       CliTrigType.Json,
	CliTrigNoColor:    CliTrigType.NoColor,
	CliTrigList:       CliTrigType.List,
	CliTrigInfo:       CliTrigType.Info,
	CliTrigFlashRead:  CliTrigType.FlashRead,
	CliTrigFlashWrite: CliTrigType.FlashWrite,
}
