package code

/* This file is automatically generated */
//######################################//

type ErrType byte

const (
	ErrReceivedMessageIsInvalid     ErrType = 5
	ErrFailedToActOnReceivedMessage ErrType = 6
	ErrInvalidCRCInMessage          ErrType = 7

	ErrFlashWriteError      ErrType = 8
	ErrFlashReadError       ErrType = 9
	ErrFlashReadLengthError ErrType = 10

	ErrDeflateError ErrType = 11
)

const (
	ErrTextReceivedMessageIsInvalid     = "Received message is invalid"
	ErrTextFailedToActOnReceivedMessage = "Failed to act on received message"
	ErrTextInvalidCRCInMessage          = "Invalid CRC in message"

	ErrTextFlashWriteError      = "Flash write error"
	ErrTextFlashReadError       = "Flash read error"
	ErrTextFlashReadLengthError = "Flash read length error"

	ErrTextDeflateError = "Deflate error"
)

var ErrMap = map[ErrType]string{
	ErrReceivedMessageIsInvalid:     ErrTextReceivedMessageIsInvalid,
	ErrFailedToActOnReceivedMessage: ErrTextFailedToActOnReceivedMessage,
	ErrInvalidCRCInMessage:          ErrTextInvalidCRCInMessage,
	ErrFlashWriteError:              ErrTextFlashWriteError,
	ErrFlashReadError:               ErrTextFlashReadError,
	ErrFlashReadLengthError:         ErrTextFlashReadLengthError,
	ErrDeflateError:                 ErrTextDeflateError,
}

func (obj ErrType) String() string {
	val, ok := ErrMap[obj]
	if ok {
		return val
	}
	return "Unknown ErrType"
}
