package code

/* This file is automatically generated */
//######################################//

type OpType byte

const (
	OpFlashBegin    OpType = 2
	OpFlashData     OpType = 3
	OpFlashEnd      OpType = 4
	OpMemoryBegin   OpType = 5
	OpMemoryEnd     OpType = 6
	OpMemoryData    OpType = 7
	OpSync          OpType = 8
	OpWriteRegister OpType = 9
	OpReadRegister  OpType = 10

	OpSpiSetParams      OpType = 11
	OpSpiAttachFlash    OpType = 13
	OpReadFlash         OpType = 14
	OpChangeBaudrate    OpType = 15
	OpFlashDeflateBegin OpType = 16
	OpFlashDeflateLData OpType = 17
	OpFlashDeflateLEnd  OpType = 18
	OpSpiFlashMD5       OpType = 19

	OpEraseFlash    OpType = 208
	OpEraseRegion   OpType = 209
	OpReadFlashFast OpType = 210
	OpRunUserCode   OpType = 211
)

const (
	OpTextFlashBegin    = "Flash Begin"
	OpTextFlashData     = "Flash Data"
	OpTextFlashEnd      = "Flash End"
	OpTextMemoryBegin   = "Memory Begin"
	OpTextMemoryEnd     = "Memory End"
	OpTextMemoryData    = "Memory Data"
	OpTextSync          = "Sync"
	OpTextWriteRegister = "Write Register"
	OpTextReadRegister  = "Read Register"

	OpTextSpiSetParams      = "Spi Set Params"
	OpTextSpiAttachFlash    = "Spi Attach Flash"
	OpTextReadFlash         = "Read Flash"
	OpTextChangeBaudrate    = "Change Baudrate"
	OpTextFlashDeflateBegin = "Flash Deflate Begin"
	OpTextFlashDeflateLData = "Flash Deflate lData"
	OpTextFlashDeflateLEnd  = "Flash Deflate lEnd"
	OpTextSpiFlashMD5       = "Spi Flash MD5"

	OpTextEraseFlash    = "Erase Flash"
	OpTextEraseRegion   = "Erase Region"
	OpTextReadFlashFast = "Read Flash Fast"
	OpTextRunUserCode   = "Run User Code"
)

var OpMap = map[OpType]string{
	OpFlashBegin:        OpTextFlashBegin,
	OpFlashData:         OpTextFlashData,
	OpFlashEnd:          OpTextFlashEnd,
	OpMemoryBegin:       OpTextMemoryBegin,
	OpMemoryEnd:         OpTextMemoryEnd,
	OpMemoryData:        OpTextMemoryData,
	OpSync:              OpTextSync,
	OpWriteRegister:     OpTextWriteRegister,
	OpReadRegister:      OpTextReadRegister,
	OpSpiSetParams:      OpTextSpiSetParams,
	OpSpiAttachFlash:    OpTextSpiAttachFlash,
	OpReadFlash:         OpTextReadFlash,
	OpChangeBaudrate:    OpTextChangeBaudrate,
	OpFlashDeflateBegin: OpTextFlashDeflateBegin,
	OpFlashDeflateLData: OpTextFlashDeflateLData,
	OpFlashDeflateLEnd:  OpTextFlashDeflateLEnd,
	OpSpiFlashMD5:       OpTextSpiFlashMD5,
	OpEraseFlash:        OpTextEraseFlash,
	OpEraseRegion:       OpTextEraseRegion,
	OpReadFlashFast:     OpTextReadFlashFast,
	OpRunUserCode:       OpTextRunUserCode,
}

func (obj OpType) String() string {
	val, ok := OpMap[obj]
	if ok {
		return val
	}
	return "Unknown OpType"
}
