package code

/* This file is automatically generated */
//######################################//

type OpType byte

const (
	OpFlashBegin    OpType = 2  //0x02
	OpFlashData     OpType = 3  //0x03
	OpFlashEnd      OpType = 4  //0x04
	OpMemoryBegin   OpType = 5  //0x05
	OpMemoryEnd     OpType = 6  //0x06
	OpMemoryData    OpType = 7  //0x07
	OpSync          OpType = 8  //0x08
	OpWriteRegister OpType = 9  //0x09
	OpReadRegister  OpType = 10 //0x0a

	OpSpiSetParams      OpType = 11 //0x0b
	OpSpiAttachFlash    OpType = 13 //0x0d
	OpReadFlash         OpType = 14 //0x0e
	OpChangeBaudrate    OpType = 15 //0x0f
	OpFlashDeflateBegin OpType = 16 //0x10
	OpFlashDeflateLData OpType = 17 //0x11
	OpFlashDeflateLEnd  OpType = 18 //0x12
	OpSpiFlashMD5       OpType = 19 //0x13

	OpEraseFlash    OpType = 208 //0xd0
	OpEraseRegion   OpType = 209 //0xd1
	OpReadFlashFast OpType = 210 //0xd2
	OpRunUserCode   OpType = 211 //0xd3

	OpFlashEncryptData OpType = 212 //0xd4
)

const (
	OpTextFlashBegin    = "Flash Begin"
	OpTextFlashData     = "Flash Data"
	OpTextFlashEnd      = "Flash End"
	OpTextMemoryBegin   = "Memory Begin"
	OpTextMemoryEnd     = "Memory End"
	OpTextMemoryData    = "Memory Data"
	OpTextSync          = "Sync"
	OpTextWriteRegister = "Write Register"
	OpTextReadRegister  = "Read Register"

	OpTextSpiSetParams      = "Spi Set Params"
	OpTextSpiAttachFlash    = "Spi Attach Flash"
	OpTextReadFlash         = "Read Flash"
	OpTextChangeBaudrate    = "Change Baudrate"
	OpTextFlashDeflateBegin = "Flash Deflate Begin"
	OpTextFlashDeflateLData = "Flash Deflate lData"
	OpTextFlashDeflateLEnd  = "Flash Deflate lEnd"
	OpTextSpiFlashMD5       = "Spi Flash MD5"

	OpTextEraseFlash    = "Erase Flash"
	OpTextEraseRegion   = "Erase Region"
	OpTextReadFlashFast = "Read Flash Fast"
	OpTextRunUserCode   = "Run User Code"

	OpTextFlashEncryptData = "Flash Encrypt Data"
)

var OpMap = map[OpType]string{
	OpFlashBegin:        OpTextFlashBegin,
	OpFlashData:         OpTextFlashData,
	OpFlashEnd:          OpTextFlashEnd,
	OpMemoryBegin:       OpTextMemoryBegin,
	OpMemoryEnd:         OpTextMemoryEnd,
	OpMemoryData:        OpTextMemoryData,
	OpSync:              OpTextSync,
	OpWriteRegister:     OpTextWriteRegister,
	OpReadRegister:      OpTextReadRegister,
	OpSpiSetParams:      OpTextSpiSetParams,
	OpSpiAttachFlash:    OpTextSpiAttachFlash,
	OpReadFlash:         OpTextReadFlash,
	OpChangeBaudrate:    OpTextChangeBaudrate,
	OpFlashDeflateBegin: OpTextFlashDeflateBegin,
	OpFlashDeflateLData: OpTextFlashDeflateLData,
	OpFlashDeflateLEnd:  OpTextFlashDeflateLEnd,
	OpSpiFlashMD5:       OpTextSpiFlashMD5,
	OpEraseFlash:        OpTextEraseFlash,
	OpEraseRegion:       OpTextEraseRegion,
	OpReadFlashFast:     OpTextReadFlashFast,
	OpRunUserCode:       OpTextRunUserCode,
	OpFlashEncryptData:  OpTextFlashEncryptData,
}

func (obj OpType) String() string {
	val, ok := OpMap[obj]
	if ok {
		return val
	}
	return "Unknown OpType"
}
